parameters:
  reinhurd_fns_qr_receipt_api.api.auth_url: 'https://openapi.nalog.ru:8090/open-api/AuthService/0.1?wsdl'
  reinhurd_fns_qr_receipt_api.api.request_url: 'https://openapi.nalog.ru:8090/open-api/ais3/KktService/0.1?wsdl'
  reinhurd_fns_qr_receipt_api.master_token: '/*YOUR MASTER TOKEN HERE*/'
  reinhurd_fns_qr_receipt_api.proxy.enable: false
  reinhurd_fns_qr_receipt_api.proxy.settings: '127.0.0.1:1337'

